# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04node\"\x07\n\x05\x45mpty\"Q\n\x11\x43reateNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x17\n\x0fmax_capacity_gb\x18\x03 \x01(\x03\" \n\rNodeIdRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"0\n\x0cNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x83\x01\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x17\n\x0fmax_capacity_gb\x18\x04 \x01(\x03\x12\x18\n\x10used_capacity_gb\x18\x05 \x01(\x02\x12\x0f\n\x07is_full\x18\x06 \x01(\x08\")\n\x08NodeList\x12\x1d\n\x05nodes\x18\x01 \x03(\x0b\x32\x0e.node.NodeInfo2\xab\x01\n\x0eNodeController\x12\x39\n\nCreateNode\x12\x17.node.CreateNodeRequest\x1a\x12.node.NodeResponse\x12\x34\n\rGetNodeStatus\x12\x13.node.NodeIdRequest\x1a\x0e.node.NodeInfo\x12(\n\tListNodes\x12\x0b.node.Empty\x1a\x0e.node.NodeListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CREATENODEREQUEST']._serialized_start=29
  _globals['_CREATENODEREQUEST']._serialized_end=110
  _globals['_NODEIDREQUEST']._serialized_start=112
  _globals['_NODEIDREQUEST']._serialized_end=144
  _globals['_NODERESPONSE']._serialized_start=146
  _globals['_NODERESPONSE']._serialized_end=194
  _globals['_NODEINFO']._serialized_start=197
  _globals['_NODEINFO']._serialized_end=328
  _globals['_NODELIST']._serialized_start=330
  _globals['_NODELIST']._serialized_end=371
  _globals['_NODECONTROLLER']._serialized_start=374
  _globals['_NODECONTROLLER']._serialized_end=545
# @@protoc_insertion_point(module_scope)
