"""add_file_sharing_and_security_fields

Revision ID: cce701e03156
Revises: 7f45f9939e8b
Create Date: 2026-01-07 18:20:16.842244+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Utile pour UUID, JSONB, ARRAY

# revision identifiers, used by Alembic.
revision: str = 'cce701e03156'
down_revision: Union[str, None] = '7f45f9939e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_shares_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], name=op.f('fk_file_shares_shared_with_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_shares'))
    )
    op.create_index(op.f('ix_file_shares_id'), 'file_shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_shares_id'), table_name='file_shares')
    op.drop_table('file_shares')
    # ### end Alembic commands ###